---
apiVersion: apps/v1
kind: Deployment
metadata:
      name: front-end
      namespace: sock-shop
spec:
      selector:
            matchLabels:
                  name: front-end
      replicas: 1
      template:
            metadata:
                  labels:
                        name: front-end
            spec:
                  containers:
                        - name: front-end
                          image: berndstransky/sock-shop-front-end:1.4
                          resources:
                                requests:
                                      cpu: 100m
                                      memory: 100Mi
                          ports:
                                - containerPort: 8079
                          env:
                                - name: NEW_RELIC_LICENSE_KEY
                                  value: < NEW_RELIC_LICENSE_KEY >
                                - name: NEW_RELIC_APP_NAME
                                  value: sock-shop-front-end
                                - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
                                  value: "true"
                                - name: NEW_RELIC_LOG_FILE_NAME
                                  value: STDOUT
                                - name: NEW_RELIC_CA_BUNDLE_PATH
                                  value: DOES_NOT_EXISTS
                          securityContext:
                                runAsNonRoot: true
                                runAsUser: 10001
                                capabilities:
                                      drop:
                                            - all
                                readOnlyRootFilesystem: true
                  nodeSelector:
                        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
      name: front-end
      labels:
            name: front-end
      namespace: sock-shop
spec:
      type: NodePort
      ports:
            - port: 80
              targetPort: 8079
              nodePort: 30001
      selector:
            name: front-end
