---
apiVersion: apps/v1
kind: Deployment
metadata:
      name: shipping
      labels:
            name: shipping
      namespace: sock-shop
spec:
      selector:
            matchLabels:
                  name: shipping
      replicas: 1
      template:
            metadata:
                  labels:
                        name: shipping
            spec:
                  containers:
                        - name: shipping
                          image: crshanks/sock-shop-shipping-nr:1.0
                          env:
                                - name: NEW_RELIC_LICENSE_KEY
                                  value: < NEW_RELIC_LICENSE_KEY >
                                - name: NEW_RELIC_APP_NAME
                                  value: "sock-shop-shipping"
                                - name: NEW_RELIC_LOG_FILE_NAME
                                  value: STDOUT
                                - name: NEW_RELIC_CA_BUNDLE_PATH
                                  value: DOES_NOT_EXISTS
                                - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
                                  value: "true"
                                - name: JAVA_OPTS
                                  value: -javaagent:/agent.jar -Dspring.sleuth.enabled=false -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
                          ports:
                                - containerPort: 80
                          securityContext:
                                runAsNonRoot: true
                                runAsUser: 10001
                                capabilities:
                                      drop:
                                            - all
                                      add:
                                            - NET_BIND_SERVICE
                                readOnlyRootFilesystem: true
                          volumeMounts:
                                - mountPath: /tmp
                                  name: tmp-volume
                  volumes:
                        - name: tmp-volume
                          emptyDir:
                                medium: Memory
                  nodeSelector:
                        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
      name: shipping
      labels:
            name: shipping
      namespace: sock-shop
spec:
      ports:
            # the port that this service should serve on
            - port: 80
              targetPort: 80
      selector:
            name: shipping
